DROP TABLE Match;
CREATE TABLE Match(
  all_gg_counts int,
  barracks_status_dire int,
  barracks_status_radiant int,
  cluster1 int,
  dire_logo varchar(255),
  dire_score int,
  dire_team_id varchar(20),
  duration1 int,
  engine int,
  first_blood_time varchar(20),
  game_mode int,
  human_players int,
  league_name varchar(50),
  leagueid varchar(50),
  match_id varchar(20) primary key,
  negative_votes int,
  positive_votes int,
  radiant_gold_adv int,
  radiant_logo varchar(255),
  radiant_score int,
  radiant_team varchar(20),
  radiant_win int,
  radiant_xp_adv int,
  region int,
  replay_url varchar(255),
  start_time varchar(12),
  tower_status_dire int,
  tower_status_radiant int,
  version1 int,
  constraint bool_radiant_win check(radiant_win in(1,0))
);